dist: bionic

language: java

jobs:
  include:
    - os: linux
      arch: amd64
      services:
        - docker
      script: docker build .
    - os: linux
      arch: arm64
      services:
        - docker
      script: docker build .