dist: bionic

language: java

services:
  - docker

jobs:
  include:
    - os: linux
      arch: amd64
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t brunoshiroma/benchtool-java:$TRAVIS_CPU_ARCH-latest .
        - docker push brunoshiroma/benchtool-java:$TRAVIS_CPU_ARCH-latest
    - os: linux
      arch: arm64
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t brunoshiroma/benchtool-java:$TRAVIS_CPU_ARCH-latest .
        - docker push brunoshiroma/benchtool-java:$TRAVIS_CPU_ARCH-latest